name: a workflow for me Hello World file
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Rich"